### ISSUE TITLE
Correctly trigger warnings when matched text is on separate lines

### ISSUE THREAD

**Issue by steveatdm** [defmethodinc/just-not-sorry#67]
If a warning is broken onto two lines, it remains highlighted:

![1](https://user-images.githubusercontent.com/45763530/74194266-f15b9280-4c26-11ea-85da-9aa56ecdf467.png)

It should be highlighted as a spelling error perhaps in this case, but not as a warning.

I originally balked when raising this because I thought it may be beneficial for keywords that are phrases, but it only triggers when a word is broken up, not when broken on a space, so there is no benefit that I can see:

![2](https://user-images.githubusercontent.com/45763530/74194272-f4568300-4c26-11ea-8242-edd922e2b59c.png)

![3](https://user-images.githubusercontent.com/45763530/74194284-fa4c6400-4c26-11ea-8337-a8758af9e6d7.png)

**Comment by sbrudz** [comment]
This issue is still occurring in the latest code on the beta branch, but it now takes a slightly different form:
<img width="474" alt="image" src="https://user-images.githubusercontent.com/1520763/105645135-4eb01a00-5e5f-11eb-8fcf-234752986324.png">

In this case, the `ju` in the "just" that's broken over two lines should not be underlined.

But the `make sense` part of "Does that make sense" caused by a word wrap should be underlined.
